from enum import Enum, auto


class StartingImage(Enum):
    CONTENT = auto()
    STYLE = auto()
    NOISE = auto()


CONTENT_WEIGHT = 1e-2
STYLE_WEIGHT = 1

CONTENT_LEARNING_RATE = 1
STYLE_LEARNING_RATE = 1e-3
TRANSFER_LEARNING_RATE = 1

CONTENT_LR_SCHEDULER_STEP = 300
STYLE_LR_SCHEDULER_STEP = 300
TRANSFER_LR_SCHEDULER_STEP = 400

CONTENT_LR_SCHEDULER_DECAY = 0.9
STYLE_LR_SCHEDULER_DECAY = 0.9
TRANSFER_LR_SCHEDULER_DECAY = 0.92

CONTENT_CONTENT_LAYER = 'relu2_1'
STYLE_STYLE_LAYERS = ['relu1_2', 'relu2_2']
TRANSFER_CONTENT_LAYER = 'relu4_2'
TRANSFER_STYLE_LAYERS = ['relu1_1', 'relu2_1', 'relu3_1', 'relu4_1']

STYLE_IMAGE = 'data/style_image.jpg'
CONTENT_IMAGE = 'data/content_image.jpg'

TRANSFER_STARTING_IMAGE_TYPE = StartingImage.CONTENT

WIDTH = 500
HEIGHT = 500
EPOCHS = 5000
IMAGE_VISUALISE_FREQUENCY = 200
